config/routes.rb
Rails.application.routes.draw do
  root 'flights#index'
  get  'flights/index', as: "flight"

  get  '/about',   to: 'static_pages#about'
end

app/models/airport.rb
class Airport < ApplicationRecord

      has_many :departing_flights, :foreign_key => "start_id", :class_name => "Flight"
      has_many :arriving_flights, :foreign_key => "finish_id", :class_name => "Flight"

      validates :name, presence: true
      validates :code, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flight.rb
class Flight < ApplicationRecord


  validates :start_id,  presence: true
  validates :finish_id, presence: true
  validates :depart,    presence: true
  validates :duration,  presence: true


end

app/controllers/airports_controller.rb
class AirportsController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  def index
    @flights = Flight.all
  end

end 

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/airports_helper.rb
module AirportsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.       # Documentation comment
  def full_title(page_title = '')                     # Method def, optional arg
    base_title = "Ruby on Rails Tutorial Sample App"  # Variable assignment
    if page_title.empty?                              # Boolean test
      base_title                                      # Implicit return
    else
      page_title + " | " + base_title                 # String concatenation
    end
  end
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/flights/_search_form.html.erb
<%= form_for(:flight, url: flight_path, method: :get) do |f| %>

  <%= f.label :start_id, "From:" %><br>
  <%= f.collection_select(:start_id, Airport.all, :code, :name) %><br>

  <%= f.label :finish_id, "To:"%><br>
  <%= f.collection_select(:finish_id, Airport.all, :code, :name) %><br>

  <%= f.label :depart, "Date:"%><br>
  <%= f.collection_select(:depart, Flight.all, :itself, :depart) %><br>

  <%= f.submit "Search" %>
<%end%>

app/views/flights/index.html.erb
<h1>Book your flight</h1>

<div class= 'container'>
  <div class= 'search'>
    <%= render partial: 'search_form', locals: {cities: @cities, dates: @dates}%>
  </div>
</div>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "sample app", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",    root_path %></li>
        <li><%= link_to "About",    about_path %></li>
        <li><%= link_to "Log in", '#' %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
  </head>
  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "sample app", '#', id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home",   '#' %></li>
            <li><%= link_to "About",   '#' %></li>
            <li><%= link_to "Log in", '#' %></li>
          </ul>
        </nav>
      </div>
    </header>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>
<div class="center jumbotron">
  <h1>Welcome to the Sample App</h1>

  <h2>
    This is the home page for the
    <a href="https://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    sample application.
  </h2>

  <%= link_to "Sign up now!", about_path, class: "btn btn-lg btn-primary" %>
</div>